apiVersion: v1
data:
    Corefile: |
        .:53 {
            errors
            health {
                lameduck 5s
            }
            ready
            kubernetes cluster.local in-addr.arpa ip6.arpa {
                pods insecure
                fallthrough in-addr.arpa ip6.arpa
                ttl 30
            }
            prometheus :9153
            forward . /etc/resolv.conf {
                max_concurrent 1000
            }
            cache 30
            loop
            reload
            loadbalance
        }
        ## Find and replace the IP address below with the ingress IP from the minikube cluster.
        pingcentral.example.com {
            hosts {
                192.168.64.20		pingfederate-cluster.pingcentral.example.com
                192.168.64.20		pingfederate-admin.pingcentral.example.com
                192.168.64.20		pingfederate-engine.pingcentral.example.com
                192.168.64.20		pingdirectory.pingcentral.example.com
                192.168.64.20		pingaccess-engine.pingcentral.example.com
                192.168.64.20		pingaccess-admin.pingcentral.example.com
                fallthrough
            }
            whoami
        }

kind: ConfigMap
metadata:
    name: coredns
    namespace: kube-system
